# -*- coding: utf-8 -*-
"""Lvadsusr144_Bathri_D_IA!.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PD13gRYnOJDERJ3bSbOtmzxZ6K74LyEl
"""

#LAB SECTION 1
#1
def area(l,w):
  a = l*w
  return a
def category(ar):
  if ar>=2400:
    return "Large"
  elif ar>=1200 and ar<2400:
    return "Medium"
  else:
    return "Small"
length = float(input("Enter length of property in meter:"))
width = float(input("Enter width of poperty in meter:"))
area_of_property = area(length,width)
print("The area of property is {} and its category is {}".
      format(area_of_property,category(area_of_property)))

#2
def bmi(ht,wt):
  return (wt)/(ht*ht)
def category(bmi_index):
  if bmi_index>25:
    return "Please take good diet and workout/run 4 times a week"
  elif bmi_index>=18 and bmi_index<=25:
    return "Maintain your diet and workout 2-3 times a day"
  elif bmi_index<18:
    return "Please take more protein source foods and lift weights"
height = float(input("enter height in meters:"))
weight = float(input("enter weight in kilograms:"))
bmi_value = bmi(height,weight)
print("Your bmi is {:.2f} and {}".format(bmi_value,category(bmi_value)))

#3
def add_data(student):
  num = int(input("How many student data are you gonna enter:"))
  for i in range(num):
    stu = {}
    stu["name"]=input("enter students name:")
    stu["maths"]=input("enter maths mark:")
    stu["physics"]=input("enter physics mark:")
    student.append(stu)
def update(student):
  for i in student:
    for k in i:


students = [{"name":"bathri","maths":79,"physics":84}]
option = input("enter what you want to do (add/update/read/exit):")
while True:
  if option=="add":
    add_data(students)
    break
  if option =="exit":
    break
for i in students:
  for k,v in i.items():
    print(k,v)

#LAB SECTION 2
#4
ratings = ['a','u','ua','r']
age = int(input("enter users age:"))
if age<18:
  print("can watch only u and ua category")
elif age>=18 and age<21:
  print("cannot watch r category")
elif age>60:
  print("dont watch hectic category r")

#5
datbase = [1,2,3,4,5,6,7,8,9,10]
lis =[]
for i in datbase:
  if i%2==0:
    lis.append(i)
print(lis)

#6
password = "qwerty1234"
while True:
  passw = input("Enter password:")
  if passw == password:
    print("Welcome")
    break
  else:
    print("Oops try again!")

#LAB SECTION 3
#7
def cal_avg(fb):
  s = 0
  for i in fb:
    s+=i
  return s/len(fb)
def feedb(av):
  if av>4:
    return "Excellent Job! Maintain the standards"
  elif av>=3 and av<=4:
    return "Good!,can improve"
  else:
    return "Something is wrong with service please check and ensure"
feedbackscores = [3.5,2.9,4.1,4.8,2.1,3.9]
avg_score = cal_avg(feedbackscores)
print("average is {:.2f}".format(avg_score))
print("feedback:{}".format(feedb(avg_score)))

#8
def vow(txt):
  cnt = 0
  txt=txt.lower()
  for i in range(len(txt)):
    if txt[i]=='a' or txt[i]=='e' or txt[i]=='i' or txt[i]=='o' or txt[i]=='u':
      cnt+=1
  return cnt
text = input("Enter text:")
print("The number of vowels in the given text is:{}".format(vow(text)))

#9
import datetime
event_deadline = input("enter event deadline:")
if event_deadline == datetime.datetime.now():
  print("Your deadline has arrived")
else:
  print("you still have time to complete the task buddy!")

#LAB SECTION 4
#10

#11
flag = True
while flag:
  try:
    poll = int(input("enter poll data"))
    print("the data is in correct form")
  except ValueError:
    print("The data is not in correct form")
    flag = False

#12
def div(n1,n2):
  try:
    division = n1/n2
    return division
  except ZeroDivisionError:
    print("do not give divisor value as zero")
num1 = int(input("enter 1st number:"))
num2 = int(input("enter 2nd number:"))
div(num1,num2)

#LAB SECTION 5
#13
while True:
  with open("sample_ia1.txt","w") as files:
    log = input("enter logged details:")
    files.write(log)
    flag = input("Enter y to coninue and n to stop:")
    if flag == 'y':
      continue
    elif flag=='n':
      break
file_read = open("sample_ia1.txt","r")
print(file_read.read())

#14
flag = 1
file_name = input("ENTER FILE NAME:")
while flag:
  try:
    file = open(file_name,"r")
    print(file.read())
    break
  except:
    print("file not found")
    flag = 0

#15
while True:
  with open("sample_ia1.txt","w") as files:
    log = input("enter logged details:")
    files.write(log)
    flag = input("Enter y to coninue and n to stop:")
    if flag == 'y':
      continue
    elif flag=='n':
      break
file_read = open("sample_ia1.txt","r")
print(file_read.read())