# -*- coding: utf-8 -*-
"""LVADSUSR144_BATHRI_IA2_LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOmHJEy1Zcqcc65QIevktfpIpCGTYeyU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

data = pd.read_csv("/content/Mall_Customers.csv")

data.head()

data.isnull().sum()

data.dropna(inplace=True)

sns.heatmap(data.corr(numeric_only=True),annot=True)

scaler = MinMaxScaler()
for column in data.select_dtypes(include=['float64','int64']):
  data[column] = scaler.fit_transform(data[[column]])





